# Generated by Django 3.1.2 on 2021-03-07 13:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdsInfoModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purpose', models.CharField(max_length=10)),
                ('category', models.CharField(max_length=10)),
                ('title', models.CharField(max_length=50)),
                ('price', models.FloatField()),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='UserInfoModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=250)),
                ('phone_number', models.PositiveSmallIntegerField()),
                ('college', models.CharField(max_length=40)),
                ('branch', models.CharField(max_length=40)),
                ('address', models.CharField(max_length=50)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FavouriteAdsModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='myapp.adsinfomodel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favourite_ads', to='myapp.userinfomodel')),
            ],
        ),
        migrations.CreateModel(
            name='AdsPhotosModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photos', models.ImageField(upload_to='photos')),
                ('ads_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='myapp.adsinfomodel')),
            ],
        ),
        migrations.AddField(
            model_name='adsinfomodel',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posted_ads', to='myapp.userinfomodel'),
        ),
    ]
