# Generated by Django 3.1.2 on 2021-03-08 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20210307_2036'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfomodel',
            name='gender',
            field=models.CharField(default='Male', max_length=10),
        ),
    ]
