# Generated by Django 3.1.2 on 2021-03-09 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_userinfomodel_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfomodel',
            name='branch',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='userinfomodel',
            name='college',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='userinfomodel',
            name='description',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='userinfomodel',
            name='gender',
            field=models.CharField(blank=True, default='Male', max_length=10),
        ),
    ]
