# Generated by Django 3.1.2 on 2021-03-09 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_auto_20210309_1616'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfomodel',
            name='gender',
            field=models.CharField(blank=True, default='Male', max_length=10, null=True),
        ),
    ]
