# Generated by Django 3.1.2 on 2021-03-09 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_auto_20210309_1619'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfomodel',
            name='profile_pic',
            field=models.ImageField(blank=True, upload_to='photos/userprofilepics'),
        ),
    ]
