# Generated by Django 3.1.2 on 2021-03-09 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_userinfomodel_profile_pic'),
    ]

    operations = [
        migrations.RenameField(
            model_name='adsphotosmodel',
            old_name='ads_info',
            new_name='pic_parent',
        ),
        migrations.AlterField(
            model_name='adsinfomodel',
            name='price',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='adsphotosmodel',
            name='photo',
            field=models.ImageField(upload_to='photos/adpics'),
        ),
    ]
