# Generated by Django 3.1.2 on 2021-03-09 20:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_auto_20210310_0155'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfomodel',
            name='posted_date',
            field=models.DateField(blank=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
