# Generated by Django 3.1.2 on 2021-03-09 20:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_userinfomodel_posted_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfomodel',
            name='posted_date',
        ),
        migrations.AddField(
            model_name='adsinfomodel',
            name='posted_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
